# .readthedocs.yaml
version: 2

build:
  image: latest

python:
  version: 3.11
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
