# This configuration file contains 10 problem settings for every domain.
SEED: &id001 123  # random seed
domains:
  blocksworld:
    - ops: 4 # domain operators
      num: 3 # number of blocks
    - ops: 4
      num: 3
    - ops: 4
      num: 4
    - ops: 4
      num: 4
    - ops: 4
      num: 5
    - ops: 4
      num: 5
    - ops: 4
      num: 6
    - ops: 4
      num: 6
    - ops: 4
      num: 7
    - ops: 4
      num: 7
  depots:
    - e: 2 # depots
      i: 2 # distributors
      t: 2 # trucks
      p: 2 # pallets
      h: 2 # hoists
      c: 2 # crates
    - e: 2
      i: 3
      t: 2
      p: 2
      h: 2
      c: 2
    - e: 3
      i: 2
      t: 2
      p: 3
      h: 2
      c: 2
    - e: 3
      i: 3
      t: 3
      p: 3
      h: 3
      c: 3
    - e: 4
      i: 3
      t: 3
      p: 4
      h: 3
      c: 3
    - e: 4
      i: 4
      t: 3
      p: 4
      h: 3
      c: 3
    - e: 5
      i: 3
      t: 4
      p: 5
      h: 4
      c: 4
    - e: 5
      i: 4
      t: 4
      p: 5
      h: 4
      c: 4
    - e: 6
      i: 4
      t: 4
      p: 6
      h: 4
      c: 4
    - e: 6
      i: 5
      t: 5
      p: 6
      h: 5
      c: 5
  driverlog:
    - road_junctions: 2
      drivers: 3
      packages: 1  # incremental from 1 to 10
      trucks: 1  # drivers - 2
    - road_junctions: 2
      drivers: 3
      packages: 2
      trucks: 5  # drivers + 2
    - road_junctions: 3
      drivers: 4
      packages: 3
      trucks: 2  # drivers - 2
    - road_junctions: 3
      drivers: 4
      packages: 4
      trucks: 6  # drivers + 2
    - road_junctions: 4
      drivers: 5
      packages: 5
      trucks: 3  # drivers - 2
    - road_junctions: 4
      drivers: 5
      packages: 6
      trucks: 5  # drivers + 2
    - road_junctions: 5
      drivers: 6
      packages: 7
      trucks: 4  # drivers - 2
    - road_junctions: 5
      drivers: 6
      packages: 8
      trucks: 8  # drivers + 2
    - road_junctions: 6
      drivers: 7
      packages: 9
      trucks: 5  # drivers - 2
    - road_junctions: 6
      drivers: 7
      packages: 10
      trucks: 9  # drivers + 2
  barman:
    - num_cocktails: 2
      num_ingredients: 3
      num_shots: 3
    - num_cocktails: 2
      num_ingredients: 4
      num_shots: 3
    - num_cocktails: 3
      num_ingredients: 4
      num_shots: 4
    - num_cocktails: 3
      num_ingredients: 5
      num_shots: 4
    - num_cocktails: 4
      num_ingredients: 5
      num_shots: 5
    - num_cocktails: 4
      num_ingredients: 6
      num_shots: 5
    - num_cocktails: 5
      num_ingredients: 6
      num_shots: 6
    - num_cocktails: 5
      num_ingredients: 7
      num_shots: 6
    - num_cocktails: 6
      num_ingredients: 7
      num_shots: 7
    - num_cocktails: 6
      num_ingredients: 8
      num_shots: 7
  ferry:
    - l: 3 # number of locations
      c: 2 # number of cars = number of locations + 2
    - l: 4
      c: 2 # number of locations - 2
    - l: 5
      c: 7 # number of locations + 2
    - l: 6
      c: 4 # number of locations - 2
    - l: 7
      c: 9 # number of locations + 2
    - l: 8
      c: 6 # number of locations - 2
    - l: 9
      c: 11 # number of locations + 2
    - l: 10
      c: 8 # number of locations - 2
    - l: 11
      c: 13 # number of locations + 2
    - l: 12
      c: 10 # number of locations - 2
#  floortile:
#    - num_rows: 3 # number of rows
#      num_columns: 3 # number of columns
#      num_robots: 1 # number of robots
#      mode_flag: seq # mode (seq or time)
#    - num_rows: 3
#      num_columns: 4
#      num_robots: 2
#      mode_flag: seq
#    - num_rows: 4
#      num_columns: 3
#      num_robots: 3
#      mode_flag: seq
#    - num_rows: 4
#      num_columns: 4
#      num_robots: 4
#      mode_flag: seq
#    - num_rows: 4
#      num_columns: 5
#      num_robots: 5
#      mode_flag: seq
#    - num_rows: 5
#      num_columns: 4
#      num_robots: 6
#      mode_flag: seq
#    - num_rows: 5
#      num_columns: 5
#      num_robots: 7
#      mode_flag: seq
#    - num_rows: 5
#      num_columns: 6
#      num_robots: 8
#      mode_flag: seq
#    - num_rows: 6
#      num_columns: 5
#      num_robots: 9
#      mode_flag: seq
#    - num_rows: 6
#      num_columns: 6
#      num_robots: 10
#      mode_flag: seq
  goldminer:
    - r: 3 # number of rows
      c: 3 # number of columns
    - r: 3
      c: 4
    - r: 4
      c: 3
    - r: 4
      c: 4
    - r: 5
      c: 4
    - r: 4
      c: 5
    - r: 5
      c: 5
    - r: 6
      c: 5
    - r: 5
      c: 6
    - r: 6
      c: 6
  grid:
    - x: 3 # horizontal extension of grid
      y: 3 # vertical extension of grid
      t: 1 # number of different key and lock types
#      p: [100] # probability, for any key, to be mentioned in the goal
      k: [1] # number of keys vector (one 0 .. 9 entry for each type)
      l: [1] # number of locks vector (one 0 .. 9 entry for each type)
    - x: 4
      y: 3
      t: 1
      k: [2]
      l: [2]
    - x: 3
      y: 4
      t: 2
      k: [1, 2]
      l: [1, 1]
    - x: 4
      y: 4
      t: 2
      k: [1, 1]
      l: [2, 2]
    - x: 5
      y: 4
      t: 3
      k: [2, 2, 2]
      l: [2, 2, 2]
    - x: 4
      y: 5
      t: 3
      k: [1, 1, 2]
      l: [3, 3, 3]
    - x: 5
      y: 5
      t: 4
      k: [2, 2, 2, 2]
      l: [3, 3, 3, 3]
    - x: 6
      y: 5
      t: 4
      k: [1, 1, 2, 2]
      l: [4, 4, 4, 4]
    - x: 5
      y: 6
      t: 5
      k: [2, 2, 2, 2, 2]
      l: [3, 3, 3, 3, 3]
    - x: 6
      y: 6
      t: 5
      k: [1, 1, 2, 2, 3]
      l: [4, 4, 4, 4, 4]
  grippers:
    - n: 1 # number of robots
      r: 3 # number of rooms
      o: 1 # number of balls
    - n: 1
      r: 4
      o: 2
    - n: 1
      r: 5
      o: 2
    - n: 2
      r: 6
      o: 3
    - n: 2
      r: 7
      o: 3
    - n: 2
      r: 8
      o: 4
    - n: 3
      r: 9
      o: 4
    - n: 3
      r: 10
      o: 5
    - n: 3
      r: 11
      o: 5
    - n: 4
      r: 12
      o: 6
  hanoi:
    - n: 2 # number of discs
    - n: 3
    - n: 4
    - n: 5
    - n: 6
    - n: 7
    - n: 8
    - n: 9
    - n: 10
    - n: 11
#  matchingbw:
#    - n: 2 # number of blocks
#    - n: 3
#    - n: 4
#    - n: 5
#    - n: 6
#    - n: 7
#    - n: 8
#    - n: 9
#    - n: 10
#    - n: 11